options ls=80 pagesize=700 center nodate;
title 'Simulated ARMA Statespace model';
symbol1 v=dot color=blue i=join; 
symbol2 v=star i=none color=red;
symbol3 v=dot color=green i=join;  
data in; 
      x=10;  y=40; 
      x1=0; y1=0; 
      a1=0; b1=0; 
      iseed=123; 
      do t=-100 to 200; 
         a=rannor(iseed); 
         b=rannor(iseed); 
         dx = 0.5*x1 + 0.3*y1 + a - 0.2*a1 - 0.1*b1; 
         dy = 0.3*x1 + 0.5*y1 + b; 
         x = x + dx + .25; 
         y = y + dy + .25; 
         if t >= 0 then output; 
         x1 = dx; y1 = dy; 
         a1 = a; b1 = b; 
      end; 
      keep t x y; 
   run;
   proc gplot data=in; 
      plot  x*t=1 y*t=3 / overlay; 
   run;

  proc statespace data=in out=out lead=10 cancorr; 
      var x(1) y(1); 
      id t; 
   run;
proc gplot data=out; 
      plot for1*t=1 for2*t=1 x*t=2 y*t=2 / 
           overlay href=200.5; 
      where t > 150; 
   run;
   proc statespace data=in out=out lead=10; 
      var x(1) y(1); 
      id t; 
      form x 2 y 1; 
      restrict f(2,3)=0; 
   run;
proc print data=out; where t>= 190;run;
quit;
